app: jessie
env: hetzner-k3s
namespace: onkelmo
values:
  gitSha: "{{ .SHA }}"
  gitRepository: Bit-Barron/jessie
  image:
    repository: ghcr.io/bit-barron/jessie
    tag: "{{ .SHA }}"
  containerPort: 3000
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    host: jessie.barron.app
    tlsEnabled: true
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.57.0
